### ISSUE TITLE
I dont even know how to title this issue

### ISSUE THREAD

**Issue by t0mri** [haringsrob/laravel-dev-tools#14]
- downloaded the file from [releases page](https://github.com/haringsrob/laravel-dev-tools/releases)
- setup with [lsp-zero](https://github.com/VonHeikemen/lsp-zero.nvim)

This is my init.lua configuration:
```lua
local lsp_zero = require("lsp-zero")
local lsp_configurations = require("lspconfig.configs")

if not lsp_configurations.blade then
    lsp_configurations.blade = {
        default_config = {
            name = "blade",
            cmd = { "~/.local/share/nvim/laravel-dev-tools", "lsp" },
            filetypes = { "blade" },
            root_dir = require("lspconfig.util").root_pattern("composer.json"),
        },
    }
end

require("lspconfig").blade.setup({})
```
I got this error:
![image](https://github.com/haringsrob/laravel-dev-tools/assets/123792488/d6bbb452-65e7-4681-8beb-5115fc595905)

So i went straight to folder and tried running from the cli and i get this error:
![image](https://github.com/haringsrob/laravel-dev-tools/assets/123792488/e6a99cda-5d54-4b87-b639-252b6924ba0c)

i can not understand the error, so i cant title this issue properly, but as the creator you might get it, i hope. so pls check this out. 

author of #9 also suffered from this impaired documentation ig. so better documentation would be greatly appreciated

**Comment by nhat-tien** [comment]
I have same problem

**Comment by t0mri** [comment]
build from source, copy the bin to the your machine's bin folder and replace the path with the bin name
