### ISSUE TITLE
Couldn't start client Laravel blade lsp

### ISSUE THREAD

**Issue by furopi** [haringsrob/laravel-dev-tools#4]
I get the following error:

[Error - 12:51:21 PM] Starting client failed
Launching server using command c:\DevTools\code-insiders\data\extensions\haringsbe-haringsrob.laravel-blade-livewire-lsp-1.2.1\laravel-dev-tools failed.

Am I missing something or am I doing something wrong in the setup?

Thank you very much! 

Kind regards,
Florian

**Comment by haringsrob** [comment]
Hey @furopi,

I have not really used this with vscode lately. The code may be out of date and need to be build from scratch in order to work.

**Comment by haringsrob** [comment]
Most likely this will be an issue with a laravel version mismatch.

**Comment by furopi** [comment]
To me it looks like Windows doesn't know how to execute the binary file "laravel-dev-tools" in the extension. How can I tell windows to execute this file with the php interpreter or any file beginning with "#!/usr/bin/env php"?

Thank you! 🙃

**Comment by haringsrob** [comment]
Oof, good question, I honestly do not know :). Have you considered using docker WSL using vscode remote?

**Comment by haringsrob** [comment]
Closing this for now, I feel vscode remote is the way to go until I somehow make an executable for windows (if ever). This is a non goal at this stage of the project.

**Comment by furopi** [comment]
@haringsrob 
You actually don't need to compile a new version, you just have to exec the file with the PHP executable. And maybe add a settings option to specifiy the executable path for systems where the executable is not included in the path variable. 

It's kind of sad that there is no Windows support, what should be an easy fix :_(

**Comment by haringsrob** [comment]
Hey @furopi I am open to a PR if you have an idea on how to add support.

**Comment by furopi** [comment]
Well I'm not familiar with you code, @haringsrob , neither with github PR's but what you need to change is executing the devtools binary with "php laravel-dev-tools" instead of "./laravel-dev-tools" when running on Windows. At least from what I have tested the devtools binary runs fine than...

Hope I could help here in a little way!
