### ISSUE TITLE
How to install for Neovim???

### ISSUE THREAD

**Issue by MannyFay** [haringsrob/laravel-dev-tools#9]
Hi,

you write 'download the compiled version from releases`. Which of them exactly:
<img width="396" alt="Screenshot 2023-06-20 at 23 13 43" src="https://github.com/haringsrob/laravel-dev-tools/assets/45234439/81b440f6-3f2f-4588-b96a-07129e7c4344">

Where I have to place it / what I have to do with it?

What is with the 'path to the executable'? The place where the compile file lives???
```
  default_config = {
    -- Path to the executable: laravel-dev-generators
    cmd = { "laravel-dev-generators", "lsp" },
```

**Comment by james2doyle** [comment]
I have this working in Sublime Text with the following setup:

```sh
git clone git@github.com:haringsrob/laravel-dev-tools.git
cp laravel-dev-tools /usr/local/bin/laravel-dev-tools
```

Then I used the command `laravel-dev-tools lsp` instead of `laravel-dev-generators lsp`

**Comment by haringsrob** [comment]
Here is an example:

```
-- Configure it
configs.blade = {
    default_config = {
        cmd = { "/Users/rob/.config/lsps/laravel-dev-generators/laravel-dev-tools", "lsp" },
        filetypes = { 'blade' },
        root_dir = function(_)
            return vim.loop.cwd()
        end,
        settings = {},
    },
}
-- Set it up
lspconfig.blade.setup {
    capabilities = capabilities
}
```

**Comment by MannyFay** [comment]
@haringsrob , what you mean exactly. @james2doyle uses a clone?! Is this the outdated version the way he uses it?
Can you provide a more specific description to install and use it?
Where I have to clone/copy the repo into?
What's about the command in your example? Do I have to create a directory `lsps` in my `.config`, or is it flexible and I can choose the path?
I'm really lost about this plugin...

**Comment by haringsrob** [comment]
You can choose where you clone it. Just point to the correct "executable".

I have not made releases the last times I worked on this because it moves rather fast.

**Comment by tolyod** [comment]
> capabilities

where is `capabilities` defined? or mabt it is some typo ?
